# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'add_pass_widget.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_add_password_window(object):
    def setupUi(self, add_password_window):
        add_password_window.setObjectName("add_password_window")
        add_password_window.resize(391, 145)
        add_password_window.setMinimumSize(QtCore.QSize(391, 145))
        add_password_window.setMaximumSize(QtCore.QSize(391, 145))
        self.add_site_line = QtWidgets.QLineEdit(add_password_window)
        self.add_site_line.setGeometry(QtCore.QRect(140, 10, 231, 21))
        self.add_site_line.setObjectName("add_site_line")
        self.add_data = QtWidgets.QPushButton(add_password_window)
        self.add_data.setGeometry(QtCore.QRect(270, 100, 101, 31))
        self.add_data.setObjectName("add_data")
        self.add_login_line = QtWidgets.QLineEdit(add_password_window)
        self.add_login_line.setGeometry(QtCore.QRect(140, 40, 231, 21))
        self.add_login_line.setObjectName("add_login_line")
        self.add_pass_line = QtWidgets.QLineEdit(add_password_window)
        self.add_pass_line.setGeometry(QtCore.QRect(140, 70, 231, 21))
        self.add_pass_line.setObjectName("add_pass_line")
        self.site = QtWidgets.QLabel(add_password_window)
        self.site.setGeometry(QtCore.QRect(10, 10, 121, 21))
        self.site.setObjectName("site")
        self.login = QtWidgets.QLabel(add_password_window)
        self.login.setGeometry(QtCore.QRect(10, 40, 121, 21))
        self.login.setObjectName("login")
        self.password = QtWidgets.QLabel(add_password_window)
        self.password.setGeometry(QtCore.QRect(10, 70, 121, 21))
        self.password.setObjectName("password")

        self.retranslateUi(add_password_window)
        QtCore.QMetaObject.connectSlotsByName(add_password_window)

    def retranslateUi(self, add_password_window):
        _translate = QtCore.QCoreApplication.translate
        add_password_window.setWindowTitle(_translate("add_password_window", "Form"))
        self.add_data.setText(_translate("add_password_window", "Добавить"))
        self.site.setText(_translate("add_password_window", "Название ресурса"))
        self.login.setText(_translate("add_password_window", "Логин"))
        self.password.setText(_translate("add_password_window", "Пароль"))
