# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_gui.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.add_pass = QtWidgets.QPushButton(self.centralwidget)
        self.add_pass.setGeometry(QtCore.QRect(0, 0, 261, 101))
        self.add_pass.setObjectName("add_pass")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(260, 0, 531, 561))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.listView = QtWidgets.QListView(self.frame)
        self.listView.setGeometry(QtCore.QRect(260, 0, 256, 192))
        self.listView.setObjectName("listView")
        self.listWidget = QtWidgets.QListWidget(self.frame)
        self.listWidget.setGeometry(QtCore.QRect(0, 0, 256, 192))
        self.listWidget.setObjectName("listWidget")
        self.plainTextEdit = QtWidgets.QPlainTextEdit(self.frame)
        self.plainTextEdit.setGeometry(QtCore.QRect(0, 200, 261, 231))
        self.plainTextEdit.setObjectName("plainTextEdit")
        self.frame_2 = QtWidgets.QFrame(self.frame)
        self.frame_2.setGeometry(QtCore.QRect(0, 0, 531, 561))
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.listView_2 = QtWidgets.QListView(self.frame_2)
        self.listView_2.setGeometry(QtCore.QRect(260, 0, 256, 192))
        self.listView_2.setObjectName("listView_2")
        self.listWidget_2 = QtWidgets.QListWidget(self.frame_2)
        self.listWidget_2.setGeometry(QtCore.QRect(0, 0, 256, 192))
        self.listWidget_2.setObjectName("listWidget_2")
        self.plainTextEdit_2 = QtWidgets.QPlainTextEdit(self.frame_2)
        self.plainTextEdit_2.setGeometry(QtCore.QRect(0, 200, 261, 231))
        self.plainTextEdit_2.setObjectName("plainTextEdit_2")
        self.watch_dict = QtWidgets.QPushButton(self.centralwidget)
        self.watch_dict.setGeometry(QtCore.QRect(0, 100, 261, 101))
        self.watch_dict.setObjectName("watch_dict")
        self.watch_pass_site = QtWidgets.QPushButton(self.centralwidget)
        self.watch_pass_site.setGeometry(QtCore.QRect(0, 200, 261, 131))
        self.watch_pass_site.setObjectName("watch_pass_site")
        self.pushButton_4 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_4.setGeometry(QtCore.QRect(0, 330, 261, 111))
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_5 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_5.setGeometry(QtCore.QRect(0, 440, 261, 121))
        self.pushButton_5.setObjectName("pushButton_5")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.add_pass.setText(_translate("MainWindow", "Добавить пароль"))
        self.watch_dict.setText(_translate("MainWindow", "Показать список паролей"))
        self.watch_pass_site.setText(_translate("MainWindow", "Показать пароль для определённого сайта"))
        self.pushButton_4.setText(_translate("MainWindow", "Показать список паролей"))
        self.pushButton_5.setText(_translate("MainWindow", "Показать список паролей"))
